name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "your-gcp-project-id" # TODO: Replace with your Google Cloud project ID
  GAR_LOCATION: "your-gar-location" # TODO: Replace with your Artifact Registry location (e.g., us-central1)
  GAR_REPOSITORY: "your-gar-repo-name" # TODO: Replace with your Artifact Registry repository name
  SERVICE_NAME: "your-cloud-run-service-name" # TODO: Replace with your Cloud Run service name
  REGION: "your-cloud-run-region" # TODO: Replace with your Cloud Run region (e.g., us-central1)

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        # Replace with your Workload Identity Federation details
        workload_identity_provider: 'projects/your-gcp-project-number/locations/global/workloadIdentityPools/your-pool-name/providers/your-provider-name' # TODO: Replace with your WIF provider
        service_account: 'your-service-account-email' # TODO: Replace with your Service Account email

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" \
          --region ${{ env.REGION }} \
          --platform "managed" \
          --quiet
